<?php

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function cu_digital_campaign_bundle_secure_permissions_roles() {
  return array(
    'campaign_manager',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */

function cu_digital_campaign_bundle_secure_permissions($role) {
   $permissions = array(
    'campaign_manager' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'publish embeds',
      'unpublish embeds',
    ),
    'developer' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'publish embeds',
      'unpublish embeds',
    ),
    'site_owner' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'publish embeds',
      'unpublish embeds',
    ),
    'anonymous user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
    ),
    'authenticated user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
    ),

  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

