<?php

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function cu_digital_campaign_bundle_secure_permissions_roles() {
  return array(
    'campaign_manager',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function cu_digital_campaign_bundle_secure_permissions($role) {
  $permissions = array(
    'campaign_manager' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'developer' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view any et_beans_bean bean',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'site_owner' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view any et_beans_bean bean',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'administrator' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'anonymous user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'view twitter embeds',
      'view doubleclick embeds',
      'view facebook embeds',
    ),
    'authenticated user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'view twitter embeds',
      'view doubleclick embeds',
      'view facebook embeds',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

