<?php

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function cu_digital_campaign_bundle_secure_permissions_roles() {
  return array(
    'campaign_manager',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function cu_digital_campaign_bundle_secure_permissions($role) {
  $permissions = array(
    'campaign_manager' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
      'access navbar',
      'view the administration theme',
      'access content overview',
      'administer nodes',
    ),
    'developer' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view any et_beans_bean bean',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'site_owner' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view any et_beans_bean bean',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'administrator' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'edit et_slate_form_block embeds',
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'edit et_cupresents embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'edit facebook embeds',
      'view facebook embeds',
      'edit doubleclick embeds',
      'view doubleclick embeds',
      'edit twitter embeds',
      'view twitter embeds',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
    'anonymous user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'view twitter embeds',
      'view doubleclick embeds',
      'view facebook embeds',
    ),
    'authenticated user' => array(
      'view et_slate_form_bean embeds',
      'view et_slate_form_block embeds',
      'view et_cupresents embeds',
      'view any et_beans_bean bean',
      'view twitter embeds',
      'view doubleclick embeds',
      'view facebook embeds',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_express_help()
 *
 * Add contextual help for the Advanced content like Quicktabs.
 *
 * @param $variables
 *   Array with information about help hooks
 * @return $variables
 */
function cu_digital_campaign_bundle_express_help($variables) {

  $variables['admin/content/embeds'][] = array(
    'title' => 'Embeds Overview Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1516',
  );

  $variables['admin/content/embeds/add'][] = array(
    'title' => 'Embeds Overview Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1516',
  );

  $variables['admin/content/embeds/add/doubleclick'][] = array(
    'title' => 'Doubleclick Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  $variables['admin/content/embeds/doubleclick/%/edit'][] = array(
    'title' => 'Doubleclick Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  $variables['admin/content/embeds/add/twitter'][] = array(
    'title' => 'Twitter Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  $variables['admin/content/embeds/twitter/%/edit'][] = array(
    'title' => 'Twitter Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  $variables['admin/content/embeds/add/facebook'][] = array(
    'title' => 'Facebook Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  $variables['admin/content/embeds/facebook/%/edit'][] = array(
    'title' => 'Facebook Embed Help',
    'short_title' => 'Embed Help',
    'url' => '/node/1574',
  );

  /*
   * Don't know what is happening with Slate Form help.
  $variables['admin/content/embeds/add/et_slate_form_bean'][] = array(
    'title' => 'Slate Form Embed Help',
    'short_title' => 'Slate Help',
    'url' => '/node/444',
  );

  $variables['admin/content/embeds/et_slate_form_bean/%/edit'][] = array(
    'title' => 'Slate Form Embed Help',
    'short_title' => 'Slate Help',
    'url' => '/node/444',
  );
  */

  return $variables;
}

/**
 * Implements hook_form_alter().
 */
function cu_digital_campaign_bundle_form_embed_templates_overview_form_alter(&$form, &$form_state) {

  // Remove the descriptions so that the search form renders better horizontally.
  foreach ($form['search'] as $key => $value) {
    if (isset($value['#description'])) {
      unset($form['search'][$key]['#description']);
    }
  }
}
