<?php

/**
 * @file
 * Drupal hooks for et_cupresents module.
 */

/**
 * Callback to generate form components for CU Presents embed type.
 *
 * @param $form
 * @param $form_state
 * @param null $id
 * @param array $data
 */
function et_cupresents_form_options(&$form, &$form_state, $id = NULL, $data = array()) {

  // No block or bean will need to have a path.
  $form['embed']['path']['#access'] = FALSE;

  $form['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Embed Data'),
    '#weight' => -10,
  );

  $form['options']['series'] = array(
    '#title' => t('Series'),
    '#description' => t('The ID of the event category you wish to display.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['series']) ? $data['series'] : '',
    '#required' => TRUE,
  );

  $form['options']['include_custom'] = array(
    '#title' => t('Custom'),
    '#description' => t('I have no idea what this means.'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['include_custom']) ? $data['include_custom'] : 1,
    '#required' => FALSE,
  );
}

/**
 * Implements hook_embed_templates_types().
 *
 * @return array
 *   List of custom embed types.
 */
function et_cupresents_embed_templates_types() {
  $custom_types = array();
  $module_path = drupal_get_path('module', 'et_cupresents');
  $default_status = 'unpublished';

  $custom_types['et_cupresents'] = array(
    'label' => 'CU Presents Event Block',
    'form_callback' => 'et_cupresents_form_options',
    'submission_callback' => 'et_beans_bean_form_submit',
    'renderer' => 'bean',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/events-block',
  );

  return $custom_types;
}
